#!/usr/bin/env bash

# log_file="$HOME/.config/sway/log/focus_or_open.log"

# アプリケーションごとのプロセス名を指定する関数
get_app_process_name() {
  case "$1" in
    "alacritty")
      echo "alacritty"
      ;;
    "google-chrome-stable")
      echo "chrome"
      ;;
    "discord")
      echo "Discord"
      ;;
    # 別のアプリケーションが必要なら追加
    *)
      echo "$1"
      ;;
  esac
}

# 引数が指定されているか確認
if [ -n "$1" ]; then
  app_command="$1"
  app_process_name=$(get_app_process_name "$app_command")
  # echo "app_command: $1" >> "$log_file"
  # echo "app_process_name: $app_process_name" >> "$log_file"
fi

pid=$(pgrep -x "$app_process_name" | sed -n '1p')

# アプリケーションのプロセスが実行中かどうかを確認
if [ -n "$pid" ]; then
  # echo "pid: $pid" >> "$log_file"
  if swaymsg "[pid=$pid]" focus; then
    # echo "focus" >> "$log_file"
    # フォーカスが移動できた場合は何もしない
    :
  else
    # echo "open" >> "$log_file"
    # フォーカスが移動できなかった場合は新しいウィンドウを開く
    $app_command
  fi
else
  # echo "open" >> "$log_file"
  # 実行中でない場合は新しいウィンドウを開く
  $app_command
fi
