#!/bin/bash

# アプリケーションごとのプロセス名を指定する関数
get_app_process_name() {
  case "$1" in
    "alacritty")
      echo "alacritty"
      ;;
    "google-chrome-stable")
      echo "chrome"
      ;;
    # 別のアプリケーションが必要なら追加
    *)
      echo "$1"
      ;;
  esac
}

# 引数が指定されているか確認
if [ -n "$1" ]; then
  app_command="$1"
  app_process_name=$(get_app_process_name "$app_command")
fi

pid=$(pgrep -x "$app_process_name" | sed -n '1p')

# アプリケーションのプロセスが実行中かどうかを確認
if [ -n "$pid" ]; then
  if swaymsg "[pid=$pid]" focus; then
    # フォーカスが移動できた場合は何もしない
    :
  else
    # フォーカスが移動できなかった場合は新しいウィンドウを開く
    $app_command
  fi
else
  # 実行中でない場合は新しいウィンドウを開く
  $app_command
fi
