local utils = require('utils')

utils.map('i', '<C-j>', '<Plug>(skkeleton-enable)', { noremap = false })
utils.map('i', 'jk', '<Plug>(skkeleton-enable)', { noremap = false })
-- 子音があると1文字目だけうまく動かないので、1回打って消して回避している
utils.map('c', '<C-j>', '<Plug>(skkeleton-enable)ka<DEL>', { noremap = false, silent = true })
utils.map('c', 'jk', '<Plug>(skkeleton-enable)ka<DEL>', { noremap = false, silent = true })
utils.map('t', 'jk', '<Plug>(skkeleton-enable)', { noremap = false })

utils.map('i', 'jj', '<ESC>')

-- Load SKK dictionary path (generated by Nix for NixOS, fallback for other systems)
local dict_path = nil
local ok, nix_dict_path = pcall(require, 'skkeleton-dict-path')
if ok and vim.fn.filereadable(nix_dict_path) == 1 then
  dict_path = nix_dict_path
end

if not dict_path then
  local fallback_candidates = {
    '/run/current-system/sw/share/skk/SKK-JISYO.L',
    '/usr/share/skk/SKK-JISYO.L',
  }

  for _, path in ipairs(fallback_candidates) do
    if vim.fn.filereadable(path) == 1 then
      dict_path = path
      break
    end
  end
end

if not dict_path then
  local nix_store_paths = vim.fn.glob('/nix/store/*-skk-jisyo-l-*/share/skk/SKK-JISYO.L', false, true)
  if #nix_store_paths > 0 and vim.fn.filereadable(nix_store_paths[1]) == 1 then
    dict_path = nix_store_paths[1]
  end
end

local global_dictionaries = '[]'
if dict_path then
  global_dictionaries = "['" .. dict_path .. "']"
else
  vim.schedule(function()
    vim.notify('[skkeleton] SKK dictionary not found; globalDictionaries disabled', vim.log.levels.WARN)
  end)
end

vim.cmd([[
function! s:skkeleton_init() abort
  call skkeleton#config({
    \ 'debug': v:false,
    \ 'eggLikeNewline': v:true,
    \ 'userDictionary': '~/.skkeleton',
    \ 'globalDictionaries': ]] .. global_dictionaries .. [[,
    \ 'showCandidatesCount': 2,
    \ 'sources': ['skk_dictionary', 'google_japanese_input'],
    \ })
  call skkeleton#register_kanatable('rom', {
    \ 'jj': 'escape',
    \ "z\<Space>": ["\u3000", ''],
    \ })
endfunction

augroup skkeleton-initialize-pre
  autocmd!
  autocmd User skkeleton-initialize-pre call s:skkeleton_init()
augroup END
]])
