theme = "bad-wolf"
icons = "awesome"

[[block]]
block = "custom"
command = "echo \uf03d" # assumes fontawesome icons
on_click = "peek"
interval = "once"

# [[block]]
# block = "custom"
# command = "echo \uf030" # assumes fontawesome icons
# on_click = "flameshot gui -p ~/Pictures"
# interval = "once"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev","play", "next"]

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
full_format = "{percentage} {time}"
