[theme]
theme = "bad-wolf"
[icons]
icons = "awesome4"

[[block]]
block = "custom"
command = "echo \uf03d" # assumes fontawesome icons
[[block.click]]
button = "left"
cmd = "peek"

[[block]]
block = "custom"
command = "echo \uf030" # assumes fontawesome icons
[[block.click]]
button = "left"
cmd = "flameshot gui -p ~/Pictures"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = "$icon $mem_total_used_percents.eng(w:2)"

[[block]]
block = "cpu"

[[block]]
block = "load"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 10
full_format = "$icon  $percentage"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%a %d/%m %R') "
